apiVersion: v1
kind: Pod
metadata:
  name: kotlin-app
  labels:
    name: kotlin-app
spec:
  containers:
  - name: core
    image: devjunha/kotlin-app:latest
    imagePullPolicy: Always
    ports:
      - containerPort: 8080
        protocol: TCP
    resources:
      requests:
        cpu: 500m
        memory: 1000Mi